
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Dispositivo
{

    public string id_Dispositivo { get; set; }

    public string Plataforma { get; set; }

    public Nullable<int> id_Usuario { get; set; }



    public virtual tb_Usuario tb_Usuario { get; set; }

}

}
