
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Grupo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_Grupo()
    {

        this.tb_AsociarGrupoUsuario = new HashSet<tb_AsociarGrupoUsuario>();

        this.tb_Ticket = new HashSet<tb_Ticket>();

        this.tb_TipoServicioGrupo = new HashSet<tb_TipoServicioGrupo>();

    }


    public int id_Grupo { get; set; }

    public string Descripcion_grupo { get; set; }

    public string Clave_Grupo { get; set; }

    public Nullable<int> id_GrupoSuperior { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_AsociarGrupoUsuario> tb_AsociarGrupoUsuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Ticket> tb_Ticket { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_TipoServicioGrupo> tb_TipoServicioGrupo { get; set; }

}

}
