
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Ticket
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_Ticket()
    {

        this.tb_Bitacora = new HashSet<tb_Bitacora>();

        this.tb_Solucion = new HashSet<tb_Solucion>();

        this.tb_TicketBitacora = new HashSet<tb_TicketBitacora>();

        this.tb_TicketSolucion = new HashSet<tb_TicketSolucion>();

        this.tb_TicketDocumento = new HashSet<tb_TicketDocumento>();

    }


    public int id_Ticket { get; set; }

    public Nullable<int> id_UsuarioLevanta { get; set; }

    public string Titulo_ticket { get; set; }

    public string Descripcion_ticket { get; set; }

    public Nullable<int> Tipo_servicio { get; set; }

    public Nullable<int> id_Grupo { get; set; }

    public Nullable<int> id_UsuarioAsignado { get; set; }

    public Nullable<int> id_Estatus { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public Nullable<int> id_Prioridad { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Bitacora> tb_Bitacora { get; set; }

    public virtual tb_Estatus tb_Estatus { get; set; }

    public virtual tb_Grupo tb_Grupo { get; set; }

    public virtual tb_Prioridad tb_Prioridad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Solucion> tb_Solucion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_TicketBitacora> tb_TicketBitacora { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_TicketSolucion> tb_TicketSolucion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_TicketDocumento> tb_TicketDocumento { get; set; }

    public virtual tb_TipoServicio tb_TipoServicio { get; set; }

    public virtual tb_Usuario tb_Usuario { get; set; }

    public virtual tb_Usuario tb_Usuario1 { get; set; }

}

}
