
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Bitacora
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_Bitacora()
    {

        this.tb_TicketBitacora = new HashSet<tb_TicketBitacora>();

    }


    public int id_Bitacora { get; set; }

    public Nullable<int> id_Usuario { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public Nullable<int> id_Descripcion { get; set; }

    public Nullable<int> id_Estatus { get; set; }

    public Nullable<int> id_Ticket { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_TicketBitacora> tb_TicketBitacora { get; set; }

    public virtual tb_DescripcionBitacora tb_DescripcionBitacora { get; set; }

    public virtual tb_Estatus tb_Estatus { get; set; }

    public virtual tb_Ticket tb_Ticket { get; set; }

    public virtual tb_Usuario tb_Usuario { get; set; }

}

}
