
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Solucion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_Solucion()
    {

        this.tb_TicketSolucion = new HashSet<tb_TicketSolucion>();

    }


    public int id_Solucion { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public Nullable<int> id_Estatus { get; set; }

    public Nullable<int> id_Ticket { get; set; }

    public string MotivoRechazo { get; set; }

    public Nullable<int> id_CausaSolucion { get; set; }



    public virtual tb_CausaSolucion tb_CausaSolucion { get; set; }

    public virtual tb_Estatus tb_Estatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_TicketSolucion> tb_TicketSolucion { get; set; }

    public virtual tb_Ticket tb_Ticket { get; set; }

}

}
