
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_TipoServicio
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_TipoServicio()
    {

        this.tb_Ticket = new HashSet<tb_Ticket>();

        this.tb_TipoServicioGrupo = new HashSet<tb_TipoServicioGrupo>();

    }


    public int id_Servicio { get; set; }

    public string Descripcion_servicio { get; set; }

    public string clave_servicio { get; set; }

    public Nullable<int> id_ServicioSuperior { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Ticket> tb_Ticket { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_TipoServicioGrupo> tb_TipoServicioGrupo { get; set; }

}

}
